### ISSUE TITLE
"Errors" in Beginning Raku

### ISSUE THREAD

**Issue by thundergnat** [arnesom/arnesom.github.io#1]
Tried to send an email to course@perl6.eu but it was rejected.
Text below:
-------------------------
Just from a fairly quick glance through the first 100 pages:

Errors, suggestions for Beginning Raku.

Note: spelling suggestions are to regularize to English spellings. Feel free to
ignore.

-------------------------
Page 36:
<quote>but doesn’t work out with non-Boolean values:
           > my $forty-one = 41 does 'forty one'; # -> forty one
           > say $forty-one.Str;                  # -> forty one
           > say $forty-one.Int;                  # -> forty one # Not expected!
           > say +$forty-one;                     # -> forty one # Same problem
           > say $forty-one + 0;                  # -> 41 # Finally
</quote>

Section is about "but" but shows "does".

BTW, but DOES work with non-Boolean values:

     my $forty-two = "forty-two" but 42;
     say $forty-two.Int; # -> 42
     say $forty-two.Str; # -> forty-two

----------------------
Page 51: "indeces" -> indices.

----------------------
Page 53 "kan"     -> "can".
        "infinte" -> "infinite"

----------------------
Page 55:
<quote>The comma is essentil. If you drop it, the only output from the program
is a single line with «Nil».</quote>

Really? Not on my system. (Linux Mint 19.3, Raku 2019.11) In the REPL maybe?

perl6 -e'my $i = 0; say "hi" until $i++ > 10'

works as expected.

Also "essentil" -> "essential"

---------------------
Not really an error but...

Page 83(ish) May be worth mentioning that default stringification of Rats may
lead to some odd looking results. EG:

> perl6 -e'my $r = 1/3; my $s = .3333333333333; say "$r > $s ? {$r > $s}"'
> 0.333333 > 0.3333333333333 ? True

--------------------
Page 85
<quote>
    Why use put instead of say (as advocated in the book «Learning Perl 6»):
        •say on a string uses Str
        •say on a variable uses gist
    The difference is easy to miss.
        •put uses gist regardless of what it is used on
</quote>

This is exactly backwards. .say does a .gist on _everything_, it is just that
.gist on a string returns .self.

.put _does not_ do a .gist, it just does a .Str on all variables.

-------------------
Page 90 "InStr" -> "IntStr"

-------------------
Page 94, 95
May be worth mentioning, uniname only operates on one character, no matter how
many are passed. uninames works on _all_ of the passed characters.

(much like ord/ords and chr/chrs)

Also, round-trip by names:

 perl6 -e'say ‘»ö«’.uninames».uniparse.join'

-----------------------

BTW, Thanks for this! Looks like a great resource.

Cheers! Happy Holiday of your choosing.

thundergnat, aka Stephen Schulze

**Comment by arnesom** [comment]
Thank you for the feedback. I'll look closely into it,

Sorry about the email problem. It should be ok now.

**Comment by arnesom** [comment]
I have fixed everything you pointed out. A new version v1.01 is available at https://arnesom.github.io/

**Comment by interlab** [comment]
page: 24
find:
`my %a; say "%a{}";              # -> %a`
replace:
`my %a; say "%a";              # -> %a`

**Comment by arnesom** [comment]
Thank you for spotting and reporting. (Silly error, that one.)

**Comment by interlab** [comment]
Page 90
Find:
`1 2 3 4 5]X`
Replace:
`[1 2 3 4 5]X`

**Comment by interlab** [comment]
Page: 90
Find:
`1 2 3 4 5]X`
Replace:
`[1 2 3 4 5]X`

----

Page: 106
Find:
`> my $s = "abc"; $s.substr-rw(1, 1) = "QQQ"; $s.say; # -> aQQc`
Replace:
`> my $s = "abc"; $s.substr-rw(1, 1) = "QQQ"; $s.say; # -> aQQQc`

----

Page: 112
Find:
`say "1 $aaaaa 17"words`
Replace:
`say "1 $aaaaa 17".words`

----

Page: 196
repeated examples:
```
> say so "111111111111112345" ~~ /1+2345/; # -> True
> say so "111111111111112345" ~~ /1+2345/; # -> True
```

----

Page: 226
Find:
`*OUT.say $message if $message;`
Replace:
`*OUT.say($message) if $message;`

----

Page: 248
Find:
`round($diff.sum/100);`
Replace:
`round($diff/100);`
